#! /bin/sh
#
# $Id$
#
AUTORECONF=/usr/bin/autoreconf
#
printusage() {
    echo "usage: $1 [--clean | clean ]"
    exit 1
}
#
do_clean() {
    rm -rf autom4te.cache config aclocal.m4 configure aclocal.m4 Makefile.in config.h.in 
    rm -f m4/libtool.m4 m4/ltsugar.m4 m4/ltoptions.m4 m4/ltversion.m4 m4/lt~obsolete.m4
}
#
do_bootstrap() {
    if test -x $AUTORECONF; then
	$AUTORECONF --install
    else
	rm -rf autom4te.cache
	autoheader
	aclocal -I m4
	libtoolize -f -c
	automake -f -a -c
	autoconf
    fi
}
#
action=do_bootstrap
#
for opt
do
  case "$opt" in
      --clean | clean)
	  action=do_clean
	  ;;
      *)
	  printusage "$0"
	  ;;
  esac
done
$action
