#! /bin/sh
#
# $Id$
#
printusage() {
    echo "usage: $1 [--clean | clean ]"
    exit 1
}
#
do_clean() {
    rm -rf autom4te.cache
    rm -f ltmain.sh depcomp install-sh missing mkinstalldirs \
	config.sub config.guess
    test -r configure.ac -o -r configure.in && rm -f configure
    test -r Makefile.am && rm -f aclocal.m4 Makefile.in
    if [ $recurse = true ]; then
	for d in `find . -type d -print`; do
	    test -r "$d/configure.ac" -o -r "$d/configure.in" \
		&& rm -f configure
	    test -r "$d/Makefile.am" && rm -f "$d/Makefile.in"
	done
    fi
}
#
do_bootstrap() {
    rm -rf autom4te.cache
    aclocal -I m4
    libtoolize -f -c
    autoheader
    automake -f -a -c
    autoconf
}
#
action=do_bootstrap
recurse=false
#
for opt
do
  case "$opt" in
      --clean | clean)
	  action=do_clean
	  ;;
      --recursive | -r | -R )
	  recurse=true
	  ;;
      *)
	  printusage "$0"
	  ;;
  esac
done
$action
